on:
  push:
    tags:
    - "giraffe-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/giraffe-v/}" >> $GITHUB_ENV
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Install .NET dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration Release /p:NuGetVersion=${VERSION}

      - name: Test
        run: dotnet test --configuration Release /p:NuGetVersion=${VERSION} --no-build --verbosity normal

      - name: Pack
        run: dotnet pack --configuration Release /p:NuGetVersion=${VERSION} /p:PackageVersion=${VERSION} --output .

      - name: Push
        run: dotnet nuget push FSharp.Data.Validation.Giraffe.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${MTA_NUGET_KEY} --symbol-source https://symbols.nuget.org/download/symbols --symbol-api-key ${MTA_NUGET_KEY} 

        env:
          MTA_NUGET_KEY: ${{ secrets.MTA_NUGET_KEY }}